### ISSUE TITLE
Feature: User can add event to timeline

### ISSUE THREAD

**Issue by louiewhitz** [louiewhitz/the-Check-in#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add event to timeline

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user can click on a nav item or plus button that allows them to add an event to the main timeline. This timeline can be seen by all others who also add events corresponding to checking in on a loved one.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2022-11-08 at 12 04 21 PM](https://user-images.githubusercontent.com/99847558/200664188-158330bf-646a-4fb0-820c-a5483064519b.png)
![Screenshot 2022-11-08 at 12 03 48 PM](https://user-images.githubusercontent.com/99847558/200664191-e4c432d4-a0fe-41c8-a9b7-a33b8f294ee5.png)
![Screenshot 2022-11-08 at 12 21 46 PM](https://user-images.githubusercontent.com/99847558/200667980-e40509bc-9021-4a1b-af32-ec262c583db0.png)
![Screenshot 2022-11-08 at 12 21 19 PM](https://user-images.githubusercontent.com/99847558/200667981-a8ce96fe-9347-4324-b752-81f927da96ba.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Export SQL to pgweb to create database
- [ ] create database 
- [ ] download schema and data

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [ ] set up with node, fs, express, npm, webpack etc
- [ ] create module system that includes express middleware, hash routing
- [ ] add post request, and connect it to client task of add entry once HTTP tests are functioning
- [ ] add webpack config

- [ ] Update `server/index.js` to ...

- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

 - [ ] add an index.html file with CSS and script links needed to build project
 - [ ] add CSS stylesheet 
 - [ ] add tailwind config
 - [ ] add possible additional sets needed for styling
 - [ ] add scss stylesheet that is configured into css
 - [ ] 

 - [ ] add App.jsx for the initial render
 - [ ] add index.js for full render of "root" element
- [ ] Create a component to add an entry if add icon or nav tab icon is clicked
- [ ] render this add component into app.jsx to render it to the page
- [ ]  update database 
- [ ] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
